on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run action
        uses: ./
        with:
          playwright-json-path: './example-result/report.json'
      - name: Upload test traces
        uses: actions/upload-artifact@v3
        with:
          name: playwright-test-traces
          path: ./example-result/traces
          if-no-files-found: ignore
          retention-days: 1
